.PHONY: clean All

All:
	@echo "----------Building project:[ helloworld - Debug ]----------"
	@cd "helloworld" && "$(MAKE)" -f  "helloworld.mk"
clean:
	@echo "----------Cleaning project:[ helloworld - Debug ]----------"
	@cd "helloworld" && "$(MAKE)" -f  "helloworld.mk" clean
